### ISSUE TITLE
Error after upgrading to icingaweb2 2.4.1

### ISSUE THREAD

**Issue by towolf** [Mikesch-mp/icingaweb2-module-grafana#101]
We upgraded to Icinga2 2.71 and Icingaweb2 2.4.1 today and get this Stack Trace now.
```
2017-09-26T16:06:46+02:00 - ERROR - ErrorException in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php:268 with message: First parameter must either be an object or the name of an existing class
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'First parameter...', '/usr/share/icin...', 268, Array)
#1 /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php(268): property_exists(NULL, 'message')
#2 /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php(398): Icinga\Module\Grafana\ProvidedHook\Grapher->getMyPreviewHtml('ssh', '1_1_1_1', '')
#3 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/grapher.phtml(2): Icinga\Module\Grafana\ProvidedHook\Grapher->getPreviewHtml(Object(Icinga\Module\Monitoring\Object\Service))
#4 /usr/share/php/Icinga/Web/View.php(270): include('zend.view:///us...')
#5 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(3): Zend_View_Abstract->render(NULL)
#7 /usr/share/php/Icinga/Web/View.php(270): include('zend.view:///us...')
#8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#9 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/service/show.phtml(8): Zend_View_Abstract->render(NULL)
#10 /usr/share/php/Icinga/Web/View.php(270): include('zend.view:///us...')
#11 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('service/show.ph...', NULL)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#22 {main}

```

**Comment by towolf** [comment]
Sorry, my mistake. Our "Icinga Grafana" did not come back up after a reboot. Now it works again.

The module just could not connect ...
