### ISSUE TITLE
Undefined index: grafana_version

### ISSUE THREAD

**Issue by kepi** [Mikesch-mp/icingaweb2-module-grafana#134]
After pulling latest master I got error in sub when I enter configuration page:

```
#0 /usr/share/icingaweb2/modules/grafana/application/forms/Config/GeneralConfigForm.php(162): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Web/Form.php(760): Icinga\Module\Grafana\Forms\Config\GeneralConfigForm->createElements(Array)
#2 /usr/share/php/Icinga/Web/Form.php(1099): Icinga\Web\Form->create(Array)
#3 /usr/share/icingaweb2/application/forms/ConfigForm.php(88): Icinga\Web\Form->populate(Array)
#4 /usr/share/php/Icinga/Web/Form.php(1183): Icinga\Forms\ConfigForm->onRequest()
#5 /usr/share/icingaweb2/modules/grafana/application/controllers/ConfigController.php(20): Icinga\Web\Form->handleRequest()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\ConfigController->indexAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}
```

## Your Environment

* Icinga Web 2 Grafana version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.5.1 (businessprocess, cube, elasticsearch, generictts, grafana, monitoring, toplevelview)
* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Debian Stretch
* Enabled features (`icinga2 feature list`): Enabled features: api checker command compatlog elasticsearch ido-mysql influxdb mainlog notification statusdata
* Config validation (`icinga2 daemon -C`): ok

**Comment by kepi** [comment]
Thanks, working without any problem now.

**Comment by Mikesch-mp** [comment]
Your welcome, nice find btw :)
