### ISSUE TITLE
graphs are not saved -> uncaught error

### ISSUE THREAD

**Issue by kobalteule** [Mikesch-mp/icingaweb2-module-grafana#137]
Hi,

I just installed 1.2.1, (1.2.0 was working), however, I am not able to edit existing graphs or create new graphs. 

## Expected Behavior
Click on "Update graph" saves the graph.

## Current Behavior

Fatal error: Uncaught Error: Call to a member function getValue() on null in /usr/share/icingaweb2/modules/grafana/application/forms/Graph/GraphForm.php:202 Stack trace: #0 /usr/share/php/Icinga/Web/Form.php(1154): Icinga\Module\Grafana\Forms\Graph\GraphForm->onSuccess() #1 /usr/share/icingaweb2/modules/grafana/application/controllers/GraphController.php(108): Icinga\Web\Form->handleRequest() #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\GraphController->updateAction() #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('updateAction') #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #5 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #6 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web-> in /usr/share/icingaweb2/modules/grafana/application/forms/Graph/GraphForm.php on line 202

## Steps to Reproduce (for bugs)

1. go to "Edit graphs"
2. select existing graph
3. click "Upgrade graph", no change nessessary
4.

## Your Environment

* Icinga Web 2 Grafana version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): 2.8.1-1
* Operating System and version: debian9 inside docker
* Enabled features (`icinga2 feature list`): Enabled features: api checker command compatlog ido-mysql influxdb livestatus mainlog notification
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: adaptoview
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
warning/ApplyRule: Apply rule 'apt' (in /etc/icinga2/conf.d/apt.conf: 1:0-1:18) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by kobalteule** [comment]
sorry, my fault, I missed the "häkchen" for grafana-version...
