### ISSUE TITLE
Timerange menu - Service not found

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Mikesch-mp/icingaweb2-module-grafana#24]
Hi

I just upgraded to version 1.0.9 and tried to use links in timerange menu.
The use of any links causing the error
```
Service not found

#0 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/php/Icinga/Web/Controller.php(78): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(36): Icinga\Web\Controller->httpNotFound('Service not fou...')
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Monitoring\Controllers\ServiceController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```
I suspect that this is due to the fact that in my case the hostname in Icinga in the form of FQDN.

When I choose a period, then in the browser address bar the end of the url changes from this
/show?host=KOM-AD01-APP30.holding.com&service=SSH
to this
/show?host=KOM-AD01-APP30_holding_com&service=SSH&timerange=5m

**Comment by Mikesch-mp** [comment]
Hi, i guess you use graphite backend?

**Comment by Aleksey-Maksimov** [comment]
Yes

**Comment by Mikesch-mp** [comment]
Please download v1.0.10, it will fix your problem :)

**Comment by Aleksey-Maksimov** [comment]
Upgraded to 1.0.10, but Host page broken:
Can't access property 'service_description'. Property does not exist.

**Comment by Mikesch-mp** [comment]
can you please test v1.0.11

**Comment by Aleksey-Maksimov** [comment]
Solved. Thank you.

**Comment by Mikesch-mp** [comment]
Thanks for pointing out that bug :)
