### ISSUE TITLE
Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/local/www/icingaweb2/modules/grafana/library/Grafana/Helpers/Timeranges.php:137

### ISSUE THREAD

**Issue by gettoknowmii** [Mikesch-mp/icingaweb2-module-grafana#310]
<!-- Formatting tips:

```
Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters  in /usr/local/www/icingaweb2/modules/grafana/library/Grafana/Helpers/Timeranges.php:137
Stack trace:
#0 [internal function]: array_merge(Minutes: Array, Hours: Array, Days: Array, Months: Array, Years: Array, Special: Array)
#1 /usr/local/www/icingaweb2/modules/grafana/library/Grafana/Helpers/Timeranges.php(137): call_user_func_array('array_merge', Array)
#2 /usr/local/www/icingaweb2/modules/grafana/application/forms/Config/GeneralConfigForm.php(74): Icinga\Module\Grafana\Helpers\Timeranges::getTimeranges()
#3 /usr/local/www/icingaweb2/library/Icinga/Web/Form.php(776): Icinga\Module\Grafana\Forms\Config\GeneralConfigForm->createElements(Array)
#4 /usr/local/www/icingaweb2/library/Icinga/Web/Form.php(1118): Icinga\Web\Form->create(Array)
#5 /usr/local/www/icingaweb2/application/forms/ConfigForm.php(110): Icinga\Web\Form->populate(Array)
#6 /usr/local/www/icingaweb2/library/Icinga/Web/Form.php(1204): Icinga\Forms\ConfigForm->onRequest()
#7 /usr/local/www/icingaweb2/modules/grafana/application/controllers/ConfigController.php(20): Icinga\Web\Form->handleRequest()
#8 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\ConfigController->indexAction()
#9 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#10 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#13 /usr/local/www/icingaweb2/public/index.php(4): require_once('/usr/local/www/...')
#14 {main}
thrown
-->

## Expected Behavior
Login to icingaweb > modules > grafana > configuration > should allow me to configure grafana settings

## Current Behavior
Login to icingaweb > modules > grafana > configuration > produces the above error

## Possible Solution
Php code need to be changed

## Steps to Reproduce (for bugs)
install and configure icinga and icingaweb2 on a FreeBSD server. try to configure the grafana module

## Context
i am unable to display grafana graphs in icinga

## Your Environment
FreeBSD 13.1
icingaweb2-php81-2.11.4_1
icingaweb2-module-grafana-php81-1.4.2_1
icinga2-2.13.6
Icinga Web 2 Version | 2.11.4
PHP Version: 8.1.15

**Comment by Mikesch-mp** [comment]
Is this a new installation or did you update the module with an existing configuration?

**Comment by gettoknowmii** [comment]
This is a new installation. It is also with the old IDO. I don't have icingaDB - icinga writes data to influxdb which is a use as a data source on grafana to create graphs thats I want to display in icinga. 

I'm using PostgreSQL for my icinga installation

**Comment by Mikesch-mp** [comment]
i need more time (which i dont have at the moment) to do an release with a fix.
This is untested but should fix your problem. Edit `/usr/share/icingaweb2/modules/grafana`and change line 137 from
```
        return call_user_func_array('array_merge', self::$timeRanges);
```
to 
```
        return call_user_func_array('array_merge', array_values(self::$timeRanges));
```

**Comment by gettoknowmii** [comment]
that fixed my issue. Thanks
