### ISSUE TITLE
v1.4.2 dont work with PHP 8.2.7

### ISSUE THREAD

**Issue by Danrockan** [Mikesch-mp/icingaweb2-module-grafana#329]
Hello,

I have a problem with the module as below. I am using version 1.4.2 because I need to use PosgreSQL as a backend.

```
#0 [internal function]: array_merge()
#1 /usr/share/icingaweb2/modules/grafana/library/Grafana/Helpers/Timeranges.php(137): call_user_func_array()
#2 /usr/share/icingaweb2/modules/grafana/application/forms/Config/GeneralConfigForm.php(74): Icinga\Module\Grafana\Helpers\Timeranges::getTimeranges()
#3 /usr/share/php/Icinga/Web/Form.php(776): Icinga\Module\Grafana\Forms\Config\GeneralConfigForm->createElements()
#4 /usr/share/php/Icinga/Web/Form.php(1118): Icinga\Web\Form->create()
#5 /usr/share/icingaweb2/application/forms/ConfigForm.php(110): Icinga\Web\Form->populate()
#6 /usr/share/php/Icinga/Web/Form.php(1204): Icinga\Forms\ConfigForm->onRequest()
#7 /usr/share/icingaweb2/modules/grafana/application/controllers/ConfigController.php(20): Icinga\Web\Form->handleRequest()
#8 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Module\Grafana\Controllers\ConfigController->indexAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#10 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#11 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#12 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.12.0
* PHP version: 8.2.7
* PostgreSQL version: 15.3
* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.14.0-1)
* Operating System and version: Debian GNU/Linux 12 (bookworm)
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite icingadb influxdb journald livestatus opentsdb perfdata syslog
Enabled features: api checker command ido-pgsql influxdb2 mainlog notification

**Comment by haytxy** [comment]
hello,

maybe someone already knows the workaround for this issue?
most likely it is connected with Grapher.php configuration.

`Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$permission is deprecated in usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 61

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$object is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 283

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$dashboard is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 180

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$dashboarduid is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 181

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$panelId is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 182

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$orgId is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 183

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$customVars is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 184

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/Helpers/Timeranges.php on line 95

Deprecated: Creation of dynamic property Icinga\Module\Grafana\ProvidedHook\Grapher::$pngUrl is deprecated in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 228
`
Debian GNU/Linux 12 (bookworm)
Linux 6.1.0-17-amd64
PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
